// Design tokens (NoteBuddy)
export const tokens = {
  colors: {
    cream: '#FAF9F6',
    surface: '#FFFFFF',
    text: '#23486B',
    subtle: '#8A8F98',
    primary: '#2F7DAF',
    accentGreen: '#86B44B',
    accentOrange: '#F6A33D',
    indigo: '#23486B',
  },
  radius: {
    sm: '8px',
    md: '12px',
    lg: '24px',
    pill: '9999px',
  },
  shadow: {
    card: '0 6px 18px rgba(35,72,107,0.08)',
  },
  spacing: [4,8,12,16,20,24,32,48],
};

export const i18n = {
  en: {
    tagline: 'NoteBuddy — Share & Discover',
    discover: 'Discover',
    upload: 'Upload',
    subjects: 'Subjects',
    contributions: 'Contributions',
    more: 'More',
    requestNotes: 'Request Notes',
    contributeNotes: 'Contribute Notes',
    latestUploads: 'Latest uploads',
    featuredContributors: 'Top contributors',
    searchPlaceholder: 'Search notes, subjects, chapters…',
    class: 'Class',
    college: 'College',
    subject: 'Subject',
    fileType: 'File Type',
    sort: 'Sort',
    newest: 'Newest',
    mostDownloaded: 'Most Downloaded',
    mostLiked: 'Most Liked',
    topContributors: 'Top Contributors',
    view: 'View',
    download: 'Download',
    save: 'Save',
    like: 'Like',
    admin: 'Admin',
    login: 'Login',
    logout: 'Logout',
    pending: 'Pending',
    accepted: 'Accepted',
    rejected: 'Rejected',
    accept: 'Accept',
    reject: 'Reject',
    points: 'Points',
    thanksReceived: 'Thanks — Notes received! Your Knowledge Points will be reviewed.',
    developedBy: 'Developed With 💖 By',
  },
  ne: {
    tagline: 'नोटबड्डी — सेयर र खोज्नुहोस्',
    discover: 'खोज्नुहोस्',
    upload: 'अपलोड',
    subjects: 'विषय',
    contributions: 'योगदान',
    more: 'थप',
    requestNotes: 'नोट अनुरोध',
    contributeNotes: 'नोट सेयर गर्नुहोस्',
    latestUploads: 'भर्खरका अपलोड',
    featuredContributors: 'शीर्ष योगदानकर्ता',
    searchPlaceholder: 'नोट, विषय, अध्याय खोज्नुहोस्…',
    class: 'कक्षा',
    college: 'कलेज',
    subject: 'विषय',
    fileType: 'फाइल प्रकार',
    sort: 'क्रमबद्ध',
    newest: 'नयाँ',
    mostDownloaded: 'धेरै डाउनलोड',
    mostLiked: 'धेरै मन पराइएको',
    topContributors: 'शीर्ष योगदानकर्ता',
    view: 'हेर्नुहोस्',
    download: 'डाउनलोड',
    save: 'सेभ',
    like: 'मनपराउनुहोस्',
    admin: 'प्रशासक',
    login: 'लग-इन',
    logout: 'लग-आउट',
    pending: 'पेन्डिङ',
    accepted: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    accept: 'स्वीकार',
    reject: 'अस्वीकार',
    points: 'पोइन्ट्स',
    thanksReceived: 'धन्यवाद — नोट प्राप्त भयो! तपाईंको ज्ञान बिन्दु समीक्षा हुनेछ।',
    developedBy: 'मुहानसँग विकास गरिएको',
  }
};
